### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by FloRinke** [joshuajung/116117bot#9]
Puppeteer seems to have issues with the page.

```
user@host:~/repo/116117bot$ sudo docker run -it --name 116117bot -e URLS="https://123-iz.impfterminservice.de/impftermine/suche/XXXX-XXXX-XXXX/12345" -e HEADLESS="false" 116117bot
 > 116117bot@0.1.0 start /app
> ts-node index.ts 
Booting 116117bot
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at Impfbot.findAppointmentsInUrl (/app/index.ts:114:7)
    at Impfbot.runLoopStep (/app/index.ts:52:11)
Error 1, delaying next request.^C
```

Disabling the sandbox doesn't change this:
```
user@host:~/repo/116117bot$ sudo docker run -it --name 116117bot -e URLS="https://123-iz.impfterminservice.de/impftermine/suche/XXXX-XXXX-XXXX/12345" -e HEADLESS="false" -e NO_PUPPETEER_SANDBOX="true" 116117bot
> 116117bot@0.1.0 start /app
> ts-node index.ts
Booting 116117bot
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at Impfbot.findAppointmentsInUrl (/app/index.ts:114:7)
    at Impfbot.runLoopStep (/app/index.ts:52:11)
Error 1, delaying next request.
```
And again same result with explicitly enabled sandbox (`NO_PUPPETEER_SANDBOX="false"`)

**Comment by joshuajung** [comment]
This should be solved now, thanks for reporting it.
